version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    command: python process_csv.py
    depends_on:
      - db
  db:
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db_data:/var/lib/postgresql/data/pgdata